#----------------------------------------------------------------------
# This file was generated by /usr/local/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

updateIcon = PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABmJLR0QA/wD/AP+gvaeTAAAH"
    "TklEQVRYw62XXYxdVRXHf3vvc+7XfN0OA+VLgc4tUqgPmkhE+WiIsdQEMjFKeAPjg0XwIya+"
    "mPRFG198MUYNUQiNsSYIJoY0MZAgDQYporUINUI6U4odmGmHOzN3Pu45Z++9lg/3znTu9A7B"
    "pCtZL3vvs///vdZ/rb0PbDLnnLPWGi6xWWuNc85tHjebFlkREcClabrNGOM+MsKHmKpG7/08"
    "EDdg9BIwxhhV5b777vva/v37v9loNMattZeEgIjEU6dOTT722GO/fPbZZ580xqCquvHkABw8"
    "ePBxVVURiXqJbW3PgwcPPr4Rk7W8TExMPKKqWhRFkWVZKIpCQvCiEkRir8cYpCgK8d5LjEG8"
    "95LnhWR5LkVR9PXunoWq6sTExCPr2F0mpSNHjpxQVc2yLIQQVCTqYqut5+ZaOr+4rB/MX/Dm"
    "woqGEDTLcl1srWiWZaraCVqMUYvCq/dBQ+j1LMuCquqRI0dOACVrLYmIkKbpNY1Go9HVghVR"
    "rIXCB/7w3H/JcqiULapKFKVatnz9/hs5+fYiLx6bZWS4xFDNcv21A+wa30atVqHwAaNgNsjc"
    "GGMBGo1GI03Ta7z3p213IrXWJhcWQgjK2GiNr+zbwdBwlVXv8JpSSIkidrTZLqC5YmkuW96Z"
    "EZ5/ZZ5f/X6Sf7w5Qym1GAPaR5TW2sQYkwLYrZRrDHgvjNVTyqXIwoqn7YXlLLCSR0CpViz1"
    "kQRFmF/2ZNGyElKeen6WZ547jfsI7STZakIV0tRy6I+n+Ptbq4wMl5mey0gSS5I4sjzyyZ11"
    "djfqZEXk3Zk2L742x7/PrFAfKvPC8RYhnuaBL41T+MhWXOzFwEqMQpo6Xnj1ff78+hJJNeX8"
    "Ys6+z11OWrLMLXmsgShCFKFcstx0wxAP338D995+Be81M6qDZf702gIv/3OGUuqIUdhY+lsS"
    "AEgTy0KrzdMvnSOplZmZz/nyXdvZ9/mr2D/xMQYqliIIpqswESXPA3kR+OJtVzJxxxVMNzNs"
    "tcxTR2dZbec41z/bF41GUaxzvPxmk7OtyEIW2H3DIPfctp12lnP91TW++8A4ttPNNgjLYIwh"
    "LwruvWM7O6+t0Soip5uBYyfnSRKHyIdEYG2zzqmEV95eIiSOdojs++zl6yDeC/WhlFJq2RxR"
    "09UOGO65dYzlIlJYy7G3W3TqwfRg9RAIISAiWKOsrnrOzHtyDPWhhBuvqRJ8XKNKiIKIonqx"
    "GyCGyE3X1hioOQprOd0s8EXAGEVECCH0T4EPgeA9rZWM91cCS6IMD6cMVlwnNaYT5q2Ky3Tn"
    "oyhDtYSBwYRlVaaXA62VjOCLHvC+ZdjpdsJSVM5lykIeCb7ARy4QMP0prEUBFBGlmUVmM6GS"
    "GkQE1Yu/WycgImi3rAbKjvpIiTkjzOaRheWCSslRdEPcH7zTvFQhcYbmiueDIKS1hLG6Y6Bs"
    "yYOQirDhOdCbAlXFB2GwbGhcWSapOGaD4eRMu3sK7QtuTQdUVBFVqqnh9bOrzKvFlR07r6pQ"
    "SSD06QUXN6KuVu8cH0BTixssc/iNRaxIB0CkR3TWQKvtmV1oU00soor3kcMnlykPV7Aly13j"
    "A0Shb/TWCUg3NEaFVha4e0eVHZelVAYS/jpvOHSiyVjNERV87KyNIqBCOyjfe+4ck3OrjA06"
    "fvHqHP9atSQVx67tZW7/eIWlLIDKOk4Pgc2l5KMynMLDnxpiRWH0sio/e8vz6+NzDDphKDXr"
    "vT2KUnHwXlrlB6+2+MnL5/nNu8K20Qq5MTzy6UHKTgl9yrZvCgCcgcVC2XtdiQdvqjEXlfpo"
    "jZ+/A4/+pcnRd5dYWC3QEECVoFAfSph2VX4746iP1lgQ+MbuKndendIqFLeFeterQLv5XQuP"
    "AZZy+NauMiYx/O5sZGCkwhtROfEfz1i6ipPI92+ucfO2EppaqtZRH3DM58KD4ymP7qpwrh1x"
    "BkQvpHmjEHsI9BPkio98e2fK7m2OJ88KZ3LFVqosGmhmwhIGgyKpI1pHgZJWLa8t5pz8AK4b"
    "LtEO2nMd9yMgIQTZnJ81WyiEPaPwmbrj2CL8raVM5/BeaqkmndIbqToqxmDp6GMuVvnxVMYP"
    "bzSMlhPChr1DCAIIQGKtxXt/fmpqavqWW25pLC8vq9nU6iyw6CExyt11+MI2Q1ugLWb9BD/9"
    "RK+crIFcqqQIogIKMUZN09RMTU1Ne+/PW2ux3Yfi4hNPPPEMgHMueu9FRHSjGxWNIrpQiDbz"
    "qLmPmkhU7c5XNPZ4SaKO4LViREMUDd6Lcy4CdLEWjTHWqSrWWiYnJ4+32+1b9+7dO16tVtUY"
    "Y5MkMZu9lHY8TXvHbZIYt8ltkq7PDwwOaqlUSg4cOPDi4cOHv2OtzURkvTl1/8z0ij179hx4"
    "6KGHvjo+Pn55kiRbPlr/HwshyOTk5PlDhw49ffTo0R8ZY85p52bquZ6MtVa7ZXidc+56a23p"
    "UhAQkSLG+A5wxlqLiBj6v9gxzjmz/t92Cc1ai3POsOlK+B+8lRdmhq+BDQAAAABJRU5ErkJg"
    "gg==")

#----------------------------------------------------------------------
# This file was generated by /usr/local/bin/img2py
#
from wx.lib.embeddedimage import PyEmbeddedImage

developerIcon= PyEmbeddedImage(
    "iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAGh0lEQVRYha2XaUxUVxiGGUj6"
    "ozW1jV1+tNE2FtJWBGSRVYYZVgFZBhh2RpYBWQYEEdFBFhEGEUHADUQqaNVoYmxTG1MTa21d"
    "6hK3pP3Rpml/tbVJFax6Qea8Pd/hzhRnRKtyk5e5uZzzPu/3nXMncxwcbC5HR0cnLoXt8xe9"
    "yJO8nzhIoVA4yrdOfPQbjk5Ob8+EyIs8bRh2cKpa4eblm7dqfevl9h17b2/eOTQ6EyIv8iRv"
    "GaWwhYvPeG32wL7PTqH/0HFz79BRzKTIk7yJMZXpYFmXBR4+pQOHT6Btx75x0/bhiU0797Pp"
    "1L7rU9bRd8BO9Hy6OeRJ3sQglpXN/9D9SwUVa691Dh5Bc/fgROu2IUwn0/YhbOgehHFzH9a1"
    "7xKi+7qOfjTx5xzCxwyj5TFzyZsYxCKmzBb9eH/l+k3/bNw2jIbOAdbYtQePU9PWQazf0o/O"
    "3Qdx7Ktvceb7azh7+QZOnb2CoydOo2vgEGpat/EwfdjQ84ndfPImBrGIOWUTOLqU1rZI9XzQ"
    "2k07maUyW5FxZdNWfHPhKu6M3MWtv/7GxMQELJfZbMaNH39GS89eVDR2oW5Kl0jkTQxiEXPq"
    "LnTRr2qSajftwqrmHla9sRfTqaq5G4a6DujKG5FtaEBhdQu2Dx4WgSzXA2kMew5+jvKGTtER"
    "y1zyJgaxiDn1PXDRlRulyuYelK3vYIb6LXiSSoybUcZDkIrXtSNOV4W27j0CLo2N8U4wcW9s"
    "24H81a2ia+X1ncKbGMQi5iMB0lbUSMXGDhTUtDL9GhOepMLaNqtKeIj0kjp8cfKMvAzMGuDc"
    "pevQr25BpqEeebxTfC4r5uGJZRPAwUWTVyXlrzYhZ2UT01VuwNPVxKtrQXx+NXYNHxHA8fFx"
    "nL90FceOn8S1mz+IZyOjd/H1ucso4Z3KKm9gBTUmEIuYjwSIzTZIWRWNSC0xsrTSOjxN2Xxs"
    "TE4lmrt2g7HJitt7BxAQkwV1Uj5UiTpcvnbTui+aOvsQl7uK5fDwxLILEJail7S8lYkFNSxR"
    "vwYkzTTSFq+DSluMqsYtfMNJAtDdPwy/6CykrFjHi6hDdHYFUgqq8PuftzB44CiCE/KQXFjL"
    "tMVGEMsugN/STCkquxJLs1eyWL6pLIqxUXzeaizR6NHAX0nLzj987Ev4RGUgLq/aOm5ZbjXU"
    "KSsIBnWyngdayVXJiEEsuwCLI9OlkJQSbl7IQlKKEZpaivD0Mi4DIkgZBgoH72gdNu8Ysrb9"
    "4pXr8A5P5WPKEJlZLsYJ8TmRGeUITSsVXiqtxbsExLIL4BOeJgIEJRawoEQ9LOKTEJxUCDU3"
    "cAtLR2ffPgGmLyD64tEZ1sJ7aZaAKJOLJpVUJObQXNJ/fgUiALHsAniHaaVgTREC4vJYYHw+"
    "piqYm3ysTMbW/v0CPsZ3O109fN1dAuI4sBABNnMeJ/ImBrHsAnipk6XABD38Ypcz/2W5COCi"
    "zyU8+YfBGnTJlY/L8PMXr2LBkjhumvtkTfEib2IQyy6Ap0ojURW+MTnML1YHUlBCPlwCE9Da"
    "vXsSLn/v374zglBNLjzCUgXEMv5pIm9iEMsuwCJlouTHUy5emsUWR2cjkBu7BMbDaOoV0Id8"
    "vcfkAIbaDXD2ixVwGvu/xb2JQSy7AO7B8ZJvjA7ekRnMP3Y5nPnaVhjbQHv9Id/xDx4+FPD+"
    "vYfwnlc4/HlFPlGZzybuTQxi2QdYEidRSl+ecr5vDJYbjGKzUc33Zfjp7y7A2SeCh0wX7z0P"
    "+2yKSOfdzQGx7AK4BcVKvvyfHwXFs8LqJjwYG+eVA/fktv/y62/wUiVgoTKJKoFneBq8nlVh"
    "qcwnKgvEsgvgGhgtOsDXlpXVNk++brTu/HP03j1Ea/Pg7Bstql8UpuVKfXaFaplXZCaIZRvg"
    "gwX+UfepKk+ecq6HGrqSatweGRVBiiqNmOuuhk9EOjzUKc8vVTIjhitnEVOQ5Z/Hs+e7+v3k"
    "FZHBW5xo9uQVvrtQiZjUAlTXmzDPQwV65q5K4kp+brkpNWZiEIuYgm05qbzy6hyTN0/nFqIZ"
    "dw1OMC8KTWbOvlFsnoeaeaiSmJsy8YVEhZE3MWbNnmOSixdshcNkF15/8535pzxDxfqa3XnL"
    "aN1o89D9i8hj0stM3sQglsy0npAU8v1bL896rXeui+cfzp4hZmdPFWZGIWbyJG9iyCy7A/DU"
    "I9s8LiVX+AxJKXta9ty0p2+F9ew4eVadGSkUMthqar3+BZQlBvh+RJnZAAAAAElFTkSuQmCC")

